/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Challenge = IDL.Record({
  'id' : UserId,
  'title' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'targetValue' : IDL.Nat,
});
export const ChallengeId = IDL.Nat;
export const ChallengeProgress = IDL.Record({
  'id' : UserId,
  'userId' : UserId,
  'currentValue' : IDL.Nat,
  'challengeId' : UserId,
});
export const ChallengeProgressId = IDL.Nat;
export const DateString = IDL.Text;
export const DietLog = IDL.Record({
  'id' : UserId,
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'userId' : UserId,
  'date' : DateString,
  'calories' : IDL.Float64,
  'items' : IDL.Text,
  'mealType' : IDL.Text,
  'protein' : IDL.Float64,
  'photoId' : IDL.Opt(UserId),
});
export const DietLogId = IDL.Nat;
export const FitnessLog = IDL.Record({
  'id' : UserId,
  'duration' : IDL.Nat,
  'userId' : UserId,
  'date' : DateString,
  'steps' : IDL.Nat,
  'notes' : IDL.Text,
  'exerciseType' : IDL.Text,
});
export const FitnessLogId = IDL.Nat;
export const HealthLog = IDL.Record({
  'id' : UserId,
  'value' : IDL.Text,
  'userId' : UserId,
  'date' : DateString,
  'logType' : IDL.Text,
});
export const HealthLogId = IDL.Nat;
export const MediaItem = IDL.Record({
  'id' : UserId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'mediaType' : IDL.Text,
});
export const MediaItemId = IDL.Nat;
export const Name = IDL.Text;
export const MotivationalQuote = IDL.Record({
  'id' : UserId,
  'text' : IDL.Text,
  'author' : Name,
});
export const MotivationalQuoteId = IDL.Nat;
export const PregnancyReport = IDL.Record({
  'id' : UserId,
  'userId' : UserId,
  'date' : DateString,
  'fileId' : IDL.Opt(UserId),
  'notes' : IDL.Text,
  'doctorName' : Name,
});
export const PregnancyReportId = IDL.Nat;
export const Reminder = IDL.Record({
  'id' : UserId,
  'repeat' : IDL.Text,
  'title' : IDL.Text,
  'userId' : UserId,
  'reminderType' : IDL.Text,
  'datetime' : DateString,
});
export const ReminderId = IDL.Nat;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'lmp' : DateString,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'name' : Name,
  'role' : IDL.Text,
  'bloodPressure' : IDL.Text,
  'bloodSugar' : IDL.Text,
  'pregnancyWeek' : IDL.Nat,
  'friends' : IDL.Vec(UserId),
});
export const UserProfileId = IDL.Nat;
export const LeaderboardEntry = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'dietScore' : IDL.Float64,
  'weeklySteps' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFriend' : IDL.Func([UserId, UserId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChallenge' : IDL.Func([Challenge], [ChallengeId], []),
  'createChallengeProgress' : IDL.Func(
      [ChallengeProgress],
      [ChallengeProgressId],
      [],
    ),
  'createDietLog' : IDL.Func([DietLog], [DietLogId], []),
  'createFitnessLog' : IDL.Func([FitnessLog], [FitnessLogId], []),
  'createHealthLog' : IDL.Func([HealthLog], [HealthLogId], []),
  'createMediaItem' : IDL.Func([MediaItem], [MediaItemId], []),
  'createMotivationalQuote' : IDL.Func(
      [MotivationalQuote],
      [MotivationalQuoteId],
      [],
    ),
  'createPregnancyReport' : IDL.Func(
      [PregnancyReport],
      [PregnancyReportId],
      [],
    ),
  'createReminder' : IDL.Func([Reminder], [ReminderId], []),
  'createUserProfile' : IDL.Func([UserProfile], [UserProfileId], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriends' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Challenge = IDL.Record({
    'id' : UserId,
    'title' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'targetValue' : IDL.Nat,
  });
  const ChallengeId = IDL.Nat;
  const ChallengeProgress = IDL.Record({
    'id' : UserId,
    'userId' : UserId,
    'currentValue' : IDL.Nat,
    'challengeId' : UserId,
  });
  const ChallengeProgressId = IDL.Nat;
  const DateString = IDL.Text;
  const DietLog = IDL.Record({
    'id' : UserId,
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'userId' : UserId,
    'date' : DateString,
    'calories' : IDL.Float64,
    'items' : IDL.Text,
    'mealType' : IDL.Text,
    'protein' : IDL.Float64,
    'photoId' : IDL.Opt(UserId),
  });
  const DietLogId = IDL.Nat;
  const FitnessLog = IDL.Record({
    'id' : UserId,
    'duration' : IDL.Nat,
    'userId' : UserId,
    'date' : DateString,
    'steps' : IDL.Nat,
    'notes' : IDL.Text,
    'exerciseType' : IDL.Text,
  });
  const FitnessLogId = IDL.Nat;
  const HealthLog = IDL.Record({
    'id' : UserId,
    'value' : IDL.Text,
    'userId' : UserId,
    'date' : DateString,
    'logType' : IDL.Text,
  });
  const HealthLogId = IDL.Nat;
  const MediaItem = IDL.Record({
    'id' : UserId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'mediaType' : IDL.Text,
  });
  const MediaItemId = IDL.Nat;
  const Name = IDL.Text;
  const MotivationalQuote = IDL.Record({
    'id' : UserId,
    'text' : IDL.Text,
    'author' : Name,
  });
  const MotivationalQuoteId = IDL.Nat;
  const PregnancyReport = IDL.Record({
    'id' : UserId,
    'userId' : UserId,
    'date' : DateString,
    'fileId' : IDL.Opt(UserId),
    'notes' : IDL.Text,
    'doctorName' : Name,
  });
  const PregnancyReportId = IDL.Nat;
  const Reminder = IDL.Record({
    'id' : UserId,
    'repeat' : IDL.Text,
    'title' : IDL.Text,
    'userId' : UserId,
    'reminderType' : IDL.Text,
    'datetime' : DateString,
  });
  const ReminderId = IDL.Nat;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'lmp' : DateString,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'name' : Name,
    'role' : IDL.Text,
    'bloodPressure' : IDL.Text,
    'bloodSugar' : IDL.Text,
    'pregnancyWeek' : IDL.Nat,
    'friends' : IDL.Vec(UserId),
  });
  const UserProfileId = IDL.Nat;
  const LeaderboardEntry = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'dietScore' : IDL.Float64,
    'weeklySteps' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFriend' : IDL.Func([UserId, UserId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChallenge' : IDL.Func([Challenge], [ChallengeId], []),
    'createChallengeProgress' : IDL.Func(
        [ChallengeProgress],
        [ChallengeProgressId],
        [],
      ),
    'createDietLog' : IDL.Func([DietLog], [DietLogId], []),
    'createFitnessLog' : IDL.Func([FitnessLog], [FitnessLogId], []),
    'createHealthLog' : IDL.Func([HealthLog], [HealthLogId], []),
    'createMediaItem' : IDL.Func([MediaItem], [MediaItemId], []),
    'createMotivationalQuote' : IDL.Func(
        [MotivationalQuote],
        [MotivationalQuoteId],
        [],
      ),
    'createPregnancyReport' : IDL.Func(
        [PregnancyReport],
        [PregnancyReportId],
        [],
      ),
    'createReminder' : IDL.Func([Reminder], [ReminderId], []),
    'createUserProfile' : IDL.Func([UserProfile], [UserProfileId], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriends' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };