/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Challenge {
  'id' : UserId,
  'title' : string,
  'unit' : string,
  'description' : string,
  'isActive' : boolean,
  'targetValue' : bigint,
}
export type ChallengeId = bigint;
export interface ChallengeProgress {
  'id' : UserId,
  'userId' : UserId,
  'currentValue' : bigint,
  'challengeId' : UserId,
}
export type ChallengeProgressId = bigint;
export type DateString = string;
export interface DietLog {
  'id' : UserId,
  'fat' : number,
  'carbs' : number,
  'userId' : UserId,
  'date' : DateString,
  'calories' : number,
  'items' : string,
  'mealType' : string,
  'protein' : number,
  'photoId' : [] | [UserId],
}
export type DietLogId = bigint;
export interface FitnessLog {
  'id' : UserId,
  'duration' : bigint,
  'userId' : UserId,
  'date' : DateString,
  'steps' : bigint,
  'notes' : string,
  'exerciseType' : string,
}
export type FitnessLogId = bigint;
export interface HealthLog {
  'id' : UserId,
  'value' : string,
  'userId' : UserId,
  'date' : DateString,
  'logType' : string,
}
export type HealthLogId = bigint;
export interface LeaderboardEntry {
  'userId' : string,
  'name' : string,
  'dietScore' : number,
  'weeklySteps' : bigint,
}
export interface MediaItem {
  'id' : UserId,
  'title' : string,
  'content' : string,
  'link' : [] | [string],
  'mediaType' : string,
}
export type MediaItemId = bigint;
export interface MotivationalQuote {
  'id' : UserId,
  'text' : string,
  'author' : Name,
}
export type MotivationalQuoteId = bigint;
export type Name = string;
export interface PregnancyReport {
  'id' : UserId,
  'userId' : UserId,
  'date' : DateString,
  'fileId' : [] | [UserId],
  'notes' : string,
  'doctorName' : Name,
}
export type PregnancyReportId = bigint;
export interface Reminder {
  'id' : UserId,
  'repeat' : string,
  'title' : string,
  'userId' : UserId,
  'reminderType' : string,
  'datetime' : DateString,
}
export type ReminderId = bigint;
export type UserId = string;
export interface UserProfile {
  'id' : UserId,
  'lmp' : DateString,
  'weight' : number,
  'height' : number,
  'name' : Name,
  'role' : string,
  'bloodPressure' : string,
  'bloodSugar' : string,
  'pregnancyWeek' : bigint,
  'friends' : Array<UserId>,
}
export type UserProfileId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFriend' : ActorMethod<[UserId, UserId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChallenge' : ActorMethod<[Challenge], ChallengeId>,
  'createChallengeProgress' : ActorMethod<
    [ChallengeProgress],
    ChallengeProgressId
  >,
  'createDietLog' : ActorMethod<[DietLog], DietLogId>,
  'createFitnessLog' : ActorMethod<[FitnessLog], FitnessLogId>,
  'createHealthLog' : ActorMethod<[HealthLog], HealthLogId>,
  'createMediaItem' : ActorMethod<[MediaItem], MediaItemId>,
  'createMotivationalQuote' : ActorMethod<
    [MotivationalQuote],
    MotivationalQuoteId
  >,
  'createPregnancyReport' : ActorMethod<[PregnancyReport], PregnancyReportId>,
  'createReminder' : ActorMethod<[Reminder], ReminderId>,
  'createUserProfile' : ActorMethod<[UserProfile], UserProfileId>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriends' : ActorMethod<[UserId], Array<UserId>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];